### ISSUE TITLE
Adicionar botões de segmento da empresa como filtro

### ISSUE THREAD

**Issue by WallysFerreira** [WallysFerreira/dashboard-di2win#61]
No html do componente filtro:
- [ ] Criar uma div com class = "childDiv" e id = "segmentDiv"
- [ ] Dentro dessa div deve ter um h1 com texto "Segmento"
- [ ] Dentro dessa div deve ter outra div com class = "optionsDiv"

Na classe do componente filtro:
- [ ] Criar field "segmentos" do tipo any
- [ ] Pegar os segmentos das empresas pela API e atribuir ao field segmentos

Por último:
- [ ] Dentro da div "optionsDiv", criar um botão pra cada elemento do array "segmentos" usando o *ngFor

**Comment by Airassilva** [comment]
me add ae
